name: 'Dependency Review'

on: [ pull_request ]

permissions:
  contents: read

jobs:
  dependency_review:
    runs-on: ubuntu-latest
    outputs:
      dependency_graph_results: ${{ steps.get_dependency_review.outputs.dependency_graph_results }}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Configuration Options: https://github.com/actions/dependency-review-action/blob/main/README.md#configuration-options
      # Examples: https://github.com/actions/dependency-review-action/blob/main/docs/examples.md
      - name: Dependency Review
        id: dependency_review
        uses: actions/dependency-review-action@v3

      - name: Get Dependency Review
        id: get_dependency_review
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BASE_REF="${{ steps.dependency_review.with.base_ref || github.event.pull_request.base.sha }}"
          HEAD_REF="${{ steps.dependency_review.with.head_ref || github.event.pull_request.head.sha }}"
          REPO="${{ github.repository }}"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/$REPO/dependency-graph/compare/$BASE_REF...$HEAD_REF" \
            > "dependency-graph-compare-$BASE_REF-$HEAD_REF.json"
          echo "dependency_graph_results=dependency-graph-compare-$BASE_REF-$HEAD_REF.json" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: dependency_graph_results
          path: ${{ env.dependency_graph_results }}
